#!/usr/bin/env python3
"""Regenerate _toc.yml from the notebooks present in this folder.

Run automatically in CI before the build, so ANY .ipynb you add (or remove) is
reflected on the site without editing the table of contents by hand.

Convention:
  * index.md is the landing page (root).
  * Every *.ipynb (except checkpoints) becomes a chapter, ordered by filename.
    Prefix files numerically (01_, 02_, ...) to control their order.
"""

import glob
import os

notebooks = sorted(
    nb for nb in glob.glob("*.ipynb")
    if ".ipynb_checkpoints" not in nb
)

lines = [
    "# AUTO-GENERATED by gen_toc.py before each build. Do not edit by hand.",
    "format: jb-book",
    "root: index",
    "chapters:",
]
for nb in notebooks:
    lines.append(f"  - file: {nb[:-len('.ipynb')]}")

with open("_toc.yml", "w") as fh:
    fh.write("\n".join(lines) + "\n")

print(f"_toc.yml regenerated with {len(notebooks)} notebook(s):")
for nb in notebooks:
    print("  -", nb)
